apiVersion: v1
kind: Namespace
metadata:
  name: filebeat

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa
  namespace: filebeat
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::735911875499:role/opsschool-project-sa-filebeat" 

---

apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: filebeat
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5601

#---

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: filebeat-nginx
#  namespace: filebeat
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/enable-external-authorization: "false"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#    - host: filebeateks.dianatop.lat
#      http:
#        paths:
#          - path: "/"
#            pathType: Prefix
#            backend:
#              service:
#                name: filebeat
#                port:
#                  number: 5601
