global:
  enabled: false
  image: "hashicorp/consul:1.14.0"
  datacenter: opsschool
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
#externalServers:
#  enabled: true
#  hosts: [consul-consul-dns.consul.svc]
#  httpPort: 8500
server:
  enabled: false
client:
  enabled: true
  exposeGossipPorts: true
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  join:
    - "provider=aws tag_key=Consul tag_value=server"
#  nodeMeta:
#    pod-name: ${HOSTNAME}
#    host-ip: ${HOST_IP}
dns:
  enabled: true
connectInject:
  enabled: false

syncCatalog:
  enabled: true
  image: hashicorp/consul-k8s-control-plane:0.49.5 
