global:
  enabled: false
  image: "hashicorp/consul:1.15.2"
  datacenter: opsschool
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
client:
  enabled: true
  retry_join:
    - "provider=aws tag_key=Consul tag_value=server"
    
externalServers:
  enabled: true
  hosts: [consul-consul-dns.consul.svc]
  httpPort: 8500

  exposeGossipPorts: true
dns:
  enabled: true

syncCatalog:
  enabled: true

connectInject:
  enabled: false