global:
  enabled: false
  image: "hashicorp/consul:1.15.2"
  datacenter: opsschool
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
#externalServers:
#  enabled: true
#  hosts: [consul-consul-dns.consul.svc]
#  httpPort: 8500
server:
  replicas: 0
client:
  enabled: true
  exposeGossipPorts: true
  join:
    - "provider=aws tag_key=Consul tag_value=server"
  nodeMeta:
    pod-name: ${HOSTNAME}
    host-ip: ${HOST_IP}
dns:
  enabled: true
connectInject:
  enabled: false

syncCatalog:
  enabled: true
  image: hashicorp/consul-k8s-control-plane:0.49.5